---
# tasks file for watchtower

- name: Create watchtower container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LOG_LEVEL: "debug"
      DOCKER_API_VERSION: "1.52"
    networks:
      - name: "{{ docker_network }}"
