traefik_data_dir: "{{ data_dir }}/traefik"
traefik_dynamic_dir: "{{ traefik_data_dir }}/dynamic"
traefik_dynamic_mount: "/etc/traefik/dynamic"

traefik_basic_auth_hash: "{{ vault_traefik_basic_auth_hash }}"
