traefik_stack_name: "traefik"
traefik_app_dir: "{{ docker_dir }}/traefik"
traefik_data_dir: "{{ data_dir }}/traefik"
traefik_dynamic_dir: "{{ traefik_data_dir }}/dynamic"
traefik_dynamic_mount: "/etc/traefik/dynamic"

traefik_basic_auth_hash: "{{ vault_traefik_basic_auth_hash }}"

# Image pinning is helpful later; keep latest if you want
traefik_image: "traefik:latest"

# Inventory-facing staging/production toggle (defaults to staging)
traefik_acme_mode: staging # allowed: production|staging
traefik_acme_servers:
  production: "https://acme-v02.api.letsencrypt.org/directory"
  staging: "https://acme-staging-v02.api.letsencrypt.org/directory"
