sso_gateway_enabled: true

sso_gateway_stack_name: "sso-gateway"
sso_gateway_data_dir: "{{ docker_apps_root }}/sso_gateway"

# oauth2-proxy image
sso_gateway_image: "quay.io/oauth2-proxy/oauth2-proxy:v7.7.1"

# OIDC issuer (Keycloak realm)
sso_oidc_issuer_url: "https://{{ keycloak_fqdn }}/realms/{{ keycloak_realm }}"

# Traefik
sso_gateway_traefik_entrypoint: "websecure"
sso_gateway_traefik_certresolver: "letsencrypt"
