---
# tasks file for zigbee2mqtt

- name: "Ensure zigbee2mqtt app directory exists"
  ansible.builtin.file:
    path: "{{ zigbee2mqtt_app_dir }}"
    state: directory
    mode: "0755"

- name: "Ensure zigbee2mqtt data directory exists"
  ansible.builtin.file:
    path: "{{ zigbee2mqtt_data_dir }}"
    state: directory
    mode: "0755"

- name: "Render docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ zigbee2mqtt_app_dir }}/docker-compose.yml"
    mode: "0644"

- name: "Start stack"
  community.docker.docker_compose_v2:
    project_src: "{{ zigbee2mqtt_app_dir }}"
    project_name: "{{ zigbee2mqtt_stack_name }}"
    state: present
