---
# tasks file for vaultwarden

- name: Create vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ vaultwarden_dir }}/data:/data"
    networks:
      - name: "{{ docker_network }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.vault-secure.entrypoints: "https"
      traefik.http.routers.vault-secure.rule: "Host(`vault.{{ domain }}`)"
      traefik.http.routers.vault-secure.tls: "true"
      traefik.http.routers.vault-secure.service: "vault"
      traefik.http.services.vault.loadbalancer.server.port: "80"
      traefik.docker.network: "{{ docker_network }}"
