---
# tasks file for vaultwarden

- name: "Ensure vaultwarden app directory exists"
  ansible.builtin.file:
    path: "{{ vaultwarden_app_dir }}"
    state: directory
    mode: "0755"

- name: "Ensure vaultwarden data directory exists"
  ansible.builtin.file:
    path: "{{ vaultwarden_data_dir }}"
    state: directory
    mode: "0755"

- name: Create vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ vaultwarden_data_dir }}/data:/data"
    networks:
      - name: "{{ docker_network }}"
