---
# tasks file for portainer

- name: Create portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ data_dir }}/portainer:/data"
    security_opts:
      - no-new-privileges:true
    networks:
      - name: "{{ docker_network }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer-secure.entrypoints: "https"
      traefik.http.routers.portainer-secure.rule: "Host(`portainer_{{ inventory_hostname_short }}.{{ domain }}`)"
      traefik.http.routers.portainer-secure.tls: "true"
      traefik.http.routers.portainer-secure.service: "portainer"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.docker.network: "{{ docker_network }}"
